### ISSUE TITLE
impossible cage

### ISSUE THREAD

**Issue by andrew-buchanan** [hwatheod/retractor#10]
P1108746 Retractor offers R: 1. Ka7-b7 b7xXa8=R+. But now the pieces in NW form an impossible cage: none of them can ever be retracted.

P1271270 Retract suggests R: f7xRg8=R, but that creates impossible cage in NE corner.

Thanks for all your work!

**Comment by hwatheod** [comment]
In the latest version Retractor 2.2, the impossible cages that arise after the wrong solutions can be verified, leaving only the correct solution.
