### ISSUE TITLE
simple retractions

### ISSUE THREAD

**Issue by andrew-buchanan** [hwatheod/retractor#9]
https://pdb.dieschwalbe.de/P1271259
Last move with BTM is Qa7-a8, but Retractor does not eliminate the impossible contenders

**Comment by hwatheod** [comment]
In Retractor 2.2, the cages that arise after each of the wrong moves (Qa7xXa8 for each possible X, and a7-a8=Q) can be verified, leaving only the correct solution. The cage consists of the entire position after each wrong move, excluding the kings.
